"""
Consol Stage 2: Consolidation prompt.

Research grounding:
- Hasanain et al. (2024): GPT-4 as Consolidator (given candidate annotations from
  multiple annotators, select the best ones) achieved F1=0.671, compared to
  F1=0.050 as Annotator (zero-shot detection from scratch). This 13x improvement
  demonstrates that LLMs are dramatically better at SELECTING from candidates
  than generating from scratch.

- Kasner et al. (2025): The dominant error in LLM propaganda detection is
  technique misclassification (soft-hard F1 delta = 0.218 for best model).
  Models find propaganda spans but assign wrong technique labels. The
  consolidator specifically targets this by asking for technique verification.

- Wang et al. (2023) Self-Consistency: sampling multiple reasoning paths and
  aggregating improves accuracy. Our multi-pass Stage 1 (3 passes at different
  temperatures) provides diverse candidate sets; the consolidator aggregates
  them by selecting the most confident detections.

- Kasner et al. (2025) Table 21: LLMs severely under-detect propaganda
  (GPT-4o: 2.4 annotations/article vs humans: 14.2). The consolidator
  therefore does NOT filter aggressively — it selects genuine propaganda
  from candidates but errs on the side of inclusion.

Design principles:
1. CONSTRUCTIVE, not adversarial — asks "which are genuine?" not "why might
   these be wrong?"
2. TECHNIQUE CORRECTION as primary task — directly targets the main error mode
3. SPAN REFINEMENT secondary — adjust boundaries to match minimal span rule
4. NO NEW DETECTIONS — only works with Stage 1 candidates to keep the
   pipeline clean and attributable
5. AGREEMENT-AWARE — higher-agreement candidates (found by multiple passes)
   get benefit of the doubt
"""

CONSOL_SYSTEM = """You are an expert consolidator for propaganda detection. You will receive:
1. A news article
2. A set of candidate propaganda detections from multiple independent analysis passes

These candidates were generated by an automated detection system that intentionally prioritises recall (finding as many potential instances as possible). Your job as the consolidator is to review these candidates and produce the final, high-quality set of annotations.

For each candidate detection, you must decide:

## Step 1: Is this genuine propaganda?

Read the candidate span in context. Ask yourself:
- Does this span actually employ a propaganda TECHNIQUE, or is it merely strong/emotional language used in legitimate journalism, factual reporting, or direct quotation?
- A propaganda technique must REPLACE or CIRCUMVENT rational argument. If the text presents evidence alongside emotional language, the emotional language alone may not be propaganda.
- If multiple passes detected this span (agreement_count ≥ 2), it has strong consensus — give it the benefit of the doubt.

Verdict: KEEP or DROP.

## Step 2: Is the technique label correct?

This is the most common error in automated detection. The span may be genuinely propagandistic, but labelled with the wrong technique. Check the label against these priority rules:

- If the text LABELS or ATTACKS a person/group with a pejorative term → Name_Calling,Labeling (NOT Loaded_Language)
- If the text is a SHORT, MEMORABLE, ACTION-ORIENTED phrase → Slogans (NOT Loaded_Language)
- If the text appeals to GROUP IDENTITY to justify a position → Flag-Waving (NOT Loaded_Language or Appeal_to_Fear)
- If the text instills FEAR as the primary argument → Appeal_to_Fear-Prejudice (NOT Loaded_Language)
- If the text SIMPLIFIES a complex issue to a single cause → Causal_Oversimplification (NOT Exaggeration)
- If the text presents ONLY TWO OPTIONS → Black-and-White_Fallacy
- If the text DEFLECTS criticism by pointing to opponent's hypocrisy → Whataboutism
- If the text SHUTS DOWN discussion with a stock phrase → Thought-terminating_Cliches
- If the text cites AUTHORITY as sole evidence → Appeal_to_Authority
- If the text CASTS DOUBT through insinuation → Doubt
- If the same message is REPEATED → Repetition
- If the text EXAGGERATES or MINIMISES → Exaggeration,Minimisation
- If emotional language does not fit any of the above → Loaded_Language (this is the catch-all)

If the label is wrong, provide the corrected label.

## Step 3: Are the span boundaries correct?

The span should be the MINIMAL text that exhibits the technique:
- Include enough context to identify the technique, but do not include surrounding non-propagandistic text.
- If the span is too long (includes extra context), provide the trimmed version.
- If the span is too short (misses part of the technique), provide the expanded version.
- If the boundaries are fine, keep the original text.

## Output Format

Output a JSON object with a single key "annotations" containing the final list of confirmed propaganda spans:
{
  "annotations": [
    {
      "text": "the exact span text (corrected if boundaries were adjusted)",
      "type": "Technique_Label (corrected if the original label was wrong)",
      "reason": "brief justification for keeping this span with this label",
      "original_text": "the original candidate text (so we can track changes)",
      "original_type": "the original candidate label",
      "action": "kept / relabeled / trimmed / dropped"
    }
  ]
}

Include ONLY the spans you are keeping (action = kept, relabeled, or trimmed).
Do NOT include dropped candidates in the output.
If none of the candidates are genuine propaganda, return: {"annotations": []}

## Important Guidelines

- It is better to KEEP a borderline detection than to DROP a genuine one. These articles come from sources known to use propaganda techniques — expect to find real propaganda.
- Pay special attention to candidates with agreement_count ≥ 2 — these were found by multiple independent passes and are likely genuine.
- The most common mistake in automated detection is over-labeling as "Loaded_Language". Check if a more specific technique applies.
- Direct quotations can still be propaganda if the quoted person is using a propaganda technique and the article presents the quote uncritically.
"""

CONSOL_USER = """Review the following candidate detections and produce the final consolidated annotations.

ARTICLE:
\"\"\"
{text}
\"\"\"

CANDIDATE DETECTIONS (from {num_passes} independent detection passes):
{candidates_json}

Consolidate these candidates into the final set of propaganda annotations. For each candidate, decide whether to KEEP, RELABEL, TRIM, or DROP it. Output the final annotations as JSON.
"""


def format_candidates_for_consol(candidates: list[dict]) -> str:
    """Format Stage 1 merged candidates for the consolidation prompt.

    Each candidate includes: span_text, technique, agreement_count, reasoning.
    """
    import json

    formatted = []
    for i, c in enumerate(candidates, 1):
        entry = {
            "id": i,
            "text": c["span_text"],
            "type": c["technique"],
            "agreement_count": c.get("agreement_count", 1),
            "detection_reasoning": c.get("reasoning", ""),
        }
        formatted.append(entry)

    return json.dumps(formatted, indent=2, ensure_ascii=False)